### ISSUE TITLE
Support for Gauge Delta

### ISSUE THREAD

**Issue by ooglek** [domnikl/statsd-php#25]
Currently the $statsd->gauge() method does not support the ability to pass a flag indicating if the value passed for a given stat is a delta or an absolute value.

This is very useful if you know you need to increment or decrement a gauge but you don't know the current value.

http://statsd.readthedocs.org/en/v3.1/reference.html#gauge

**Comment by domnikl** [comment]
That is already possible. Since the `$value` parameter for `Client::gauge()` can be a string, you can just give it `"+10"` or `"-10"`. see https://github.com/domnikl/statsd-php/blob/master/lib/Client.php#L216

**Comment by ooglek** [comment]
You are absolutely correct. I figured that out a bit later after reviewing the code.

Mind if I update the documentation to reflect this ability? I can update and then issue a pull request, or if you prefer to take that on, consider this my friendly request for that documentation! :+1:

**Comment by domnikl** [comment]
I would be happy to merge a pull request from you for the documentation! :+1:

**Comment by domnikl** [comment]
Now I can close this as the PR has been merged already
