### ISSUE TITLE
Feature request: merge counts/increments for the same key in batch mode before sending them

### ISSUE THREAD

**Issue by Minnozz** [domnikl/statsd-php#29]
Example: when calling $statsd->increment('key') 3 times in one batch, this could be merged to "key:3|c" instead of three lines with "key:1|c". This saves a lot of traffic.

**Comment by domnikl** [comment]
Great idea, but that will only work when it gets called in a certain time range. Imagine a cronjob that runs for 3 minutes and calls it when it starts and when it has finished. That would falsify the results. Is there a save way to do this?

**Comment by Minnozz** [comment]
My idea behind this was to only do this when you are already using batch mode. When you start a batch, it is already your own responsibility to end/submit it at an appropriate time.

**Comment by domnikl** [comment]
Ok that sounds good
