### ISSUE TITLE
Not almost correct default package size in InetSocket::__construct

### ISSUE THREAD

**Issue by marrrvin** [domnikl/statsd-php#40]
Ethernet MTU is 1500, right, but actual payload size in worst case is:

// MTU — (Max IP Header Size) — (UDP Header Size) = 1500 — 60 — 8 = 1432

Also I guess there is a corner case in InetSocket::cutIntoMtuSizedMessages when, after $messageBatch size is calculated,  "\n" byte is added after each metric and data may not fit in safe udp payload size.

**Comment by domnikl** [comment]
fixed in 0440a2dfbf1d7d36590bcc86c03947a3abd2fee3
