### ISSUE TITLE
Timeout bug

### ISSUE THREAD

**Issue by avj83** [domnikl/statsd-php#54]
We can not setup timeout for `UdpSocket` less than 1 sec. We need to limit the time of the connection to the `statsd` server if there are problems with the network.

If you look at the documentation (http://php.net/manual/en/function.fsockopen.php) , you can see that the function can take `float` value.

```php
resource fsockopen ( string $hostname [, int $port = -1 [, int &$errno [, string &$errstr [, float $timeout = ini_get("default_socket_timeout") ]]]] )
```

Problem here:
```php    
public function __construct($host = 'localhost', $port = 8125, $timeout = null, $persistent = false, $mtu = 1500)
    {
...
        $this->timeout = ($timeout === null) ? null : (int) $timeout;
    }
```

**Comment by domnikl** [comment]
Fixed in 2.7.0, thanks for the bug report and the fix!
