### ISSUE TITLE
Code style impovments

### ISSUE THREAD

**Issue by tukataka** [domnikl/statsd-php#65]
Hi, man!
First of all - thank you for your library. It's very useful for me. But I found some old code styles.

For example tests isn't in composer psr-4 autoload. Maybe add it to composer autoload ?
It's not about bug, it's about just codestyle improvments. 
I can do it, if you're not against.

**Comment by domnikl** [comment]
Hi @tukataka,
thanks for your offering. I already did a lot of improvements and adding Psalm to check the source as well as PHPCodeSniffer.
