### ISSUE TITLE
v3.0.0 chagelog

### ISSUE THREAD

**Issue by red-led** [domnikl/statsd-php#66]
There is nothing about v3.0.0. in CHANGELOG.md
Are there any BC breaks i should know about before updating?

**Comment by mcouillard** [comment]
Good question. Looks like 7.2 is the new min, up from 5.6.

https://github.com/domnikl/statsd-php/commit/c21a67cf6fa7d6ec5d347a179fd122f546e57752

**Comment by domnikl** [comment]
oh sorry, I missed that (it's been a while ;)). Yes, 7.2 is the new minimum. Will add that to the changelog.

**Comment by domnikl** [comment]
documented in d6cfe83
