### ISSUE TITLE
Memory Usage Metrics

### ISSUE THREAD

**Issue by ilya-direct** [domnikl/statsd-php#75]
Hi!
As I see in source code in method `memory`, it invokes `count` method:
https://github.com/domnikl/statsd-php/blob/1be7e19f73754bd34ac46cc9919ee385a50246c9/src/Client.php#L197

It is considered to be `timing` instead of `count`

**Comment by domnikl** [comment]
Hi @ilya-direct, why should memory usage be a `timing`? It's a (memory) counter that is being transmitted here.

**Comment by ilya-direct** [comment]
@domnikl 

I am using [statsd_exporter](https://github.com/prometheus/statsd_exporter) and your lib to send metrics.
And as I understood from [docs](https://prometheus.io/docs/concepts/metric_types/) 
- `counter` is something increasing every time like number of orders 
- `gauges` is something, that can go up and down like current speed of the car
- `histograms` (`timing` in statsd terminology)  is like `gauges`, but with a better precise (because of additional gauges and counters)

And thats why I thing `histigrams` or `gauge` is more appropriate for measuring `memory usage` in the specific action.

P.S. I am not good at metrics, just first time integrating it and thanks for your easy-readable and well-tested lib

**Comment by domnikl** [comment]
I don't know about statsd_exporter, but `timing` in statsd is a duration value measured in milliseconds: https://github.com/statsd/statsd/blob/master/docs/metric_types.md#timing and you may have trouble measuring memory usage in ms. Changing it from counter to gauge would be a good idea, though.
